baseURL = 'https://bitcoin21ideas.github.io/herald/'
languageCode = 'en'
title = 'Herald'
theme = "hello-friend"

[params]
  # dir name of your blog content (default is `content/posts`)
  # contentTypeName = "post"

  # "light" or "dark"
  # defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  # showMenuItems = 2

  # Enable to show reading time in minutes for posts
  # showReadingTime = false

[languages]
  [languages.en.params]
    title = "Hello Friend"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Herald"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "contacts"
        name = "Contacts"
        url = "/contacts"
