baseURL = "https://bitcoin-herald.org/"
languageCode = "en-us"
title = 'Herald'
theme = "hello-friend"

# relative = true

# ignoreErrors = ["error-remote-getjson"]

[params]
  [languages]
    [languages.en.params]
      title = " "
      subtitle = " "
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      writtenBy = "Written by"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      minuteReadingTime = "min read"
      dateFormatSingle = "2006-01-02"
      dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Herald"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "contacts"
        name = "Contacts"
        url = "/contacts"
      [[languages.en.menu.main]]
        identifier = "support"
        name = "Support"
        url = "/support"
