name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0 

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.112.7'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Generate .well-known
      run: |
        mkdir -p public/.well-known/lnurlp
        echo '{
          "names": {
            "herald": "7e7224cfe0af5aaf9131af8f3e9d34ff615ff91ce2694640f1f1fee5d8febb7d",
            "tony": "7f5c2b4e48a0e9feca63a46b13cdb82489f4020398d60a2070a968caa818d75d",
            "raptor": "b6677acd112aa0f34e1c3ad46d50c4c77edc0735fe25bfbc4f7dce0b139f7e15"
          }
        }' > public/.well-known/nost.json
        echo '{
          "status":"OK",
          "tag":"payRequest",
          "commentAllowed":255,
          "callback":"https://getalby.com/lnurlp/bitherald/callback",
          "metadata":"[[\"text/identifier\",\"bitherald@getalby.com\"],[\"text/plain\",\"Sats for bitherald\"]]",
          "minSendable":1000,"maxSendable":11000000000,
          "payerData":{"name":{"mandatory":false},
          "email":{"mandatory":false},"pubkey":{"mandatory":false}},
          "nostrPubkey":"79f00d3f5a19ec806189fcab03c1be4ff81d18ee4f653c88fac41fe03570f432",
          "allowsNostr":true
          }' > public/.well-known/lnurlp/herald


    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ALEX_HERALD_FULL_ACCESS }}
        publish_dir: ./public
        cname: bitcoin-herald.org
